language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - 7.1
  - hhvm

install: travis_retry composer install

script: phpunit

after_success:
  - if [[ "`phpenv version-name`" != "7.1" ]]; then exit 0; fi
  - phpunit --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"

cache:
  directories:
    - $HOME/.composer/cache
